#!/bin/sh
#
# $FreeBSD$
#
# PROVIDE: adguardhome
# REQUIRE: NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr
name="adguardhome"

rcvar=adguardhome_enable
pidfile=/var/run/${name}.pid

stop_cmd=adguardhome_stop
status_cmd=adguardhome_status

load_rc_config adguardhome

: ${adguardhome_enable="NO"}

command=/usr/sbin/daemon
command_args="-f -P ${pidfile} /usr/local/bin/adguardhome -c /usr/local/AdGuardHome/AdGuardHome.yaml -w /usr/local/AdGuardHome --no-check-update -s run"
required_files="/usr/local/bin/adguardhome"
required_dirs="/usr/local/AdGuardHome"


adguardhome_status()
{
         if [ -n "$rc_pid" ]; then
             echo "${name} is running as pid $rc_pid."
             return 0
         else
             echo "${name} is not running."
             return 1
         fi
}

adguardhome_stop()
{
	# wait for process to exit
	if [ -n "$rc_pid" ]; then
		echo "Stopping ${name}."
		kill $rc_pid
		echo "Waiting for PIDS: $rc_pid"
		wait_for_pids $rc_pid
		echo " done."
	else
		echo "${name} is not running."
	fi
}

run_rc_command $1
