###########################################################################
# Local syslog-ng configuration filter definition [adguardhome-sync].
###########################################################################
filter f_local_adguardhome-sync {
    program("adguardhome-sync");
};
