[status]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py status
parameters:
type:script_output
message:AdGuard Home synchronization status

[apply]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py apply
parameters:
type:script_output
message:Apply AdGuard Home synchronization settings

[start]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py start
parameters:
type:script_output
message:Start AdGuard Home synchronization

[restart]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py restart
parameters:
type:script_output
message:Restart AdGuard Home synchronization

[stop]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py stop
parameters:
type:script_output
message:Stop AdGuard Home synchronization

[sync]
command:/usr/local/opnsense/scripts/Adguardhome/sync_control.py sync
parameters:
type:script_output
message:Synchronize AdGuard Home configuration
