#!/bin/sh
rm -f /var/lib/php/tmp/opnsense_menu_cache.xml /var/lib/php/tmp/opnsense_acl_cache.json
rm -f /tmp/opnsense_menu_cache.xml /tmp/opnsense_acl_cache.json
/usr/sbin/service configd restart
/usr/local/sbin/configctl syslog restart
/usr/local/sbin/configctl webgui restart >/dev/null 2>&1 || true
exit 0
